#!/bin/bash
# Описание : Сценарий для регистрации показаний датчиков в csv файл CSVed

# Укажите полный путь к файлам LOG1 и LOG2
# Пример: LOG1="/home/pi/zgo/html/dht22_humi.txt"
logfile="/home/pi/HumidityLog.csv"
logdir="/home/pi/HumidityLogs"
cells=0
flag=0
function dht21 {
#  echo Polling DHT22 every $SLEEP seconds.
    for (( ; ; ))
    do
      flag=0
# Чтение даты и времени
      mdate="$(date +%Y.%m.%d\ %H:%M:%S\;)"
# Чтение температуры (Команда 2> /dev/null для того чтобы удалить сообщения об ошибках из вывода tail)
      temperature=$(/bin/tail /sys/devices/platform/dht11@0/iio:device0/in_temp_input 2> /dev/null)
# Чтение влажности
      humidity=$(/bin/tail /sys/devices/platform/dht11@0/iio:device0/in_humidityrelative_input 2> /dev/null)

      if [ -z "$temperature" ]
      then
      {
        flag=1
      }
      fi
      if [ -z "$humidity" ]
      then
      {
        flag=1
      }
      fi
      if [ "$flag" -eq 0 ]
      then
      {
        if ! [ -f "$logfile" ]
        then
        {
          echo "Data;Temperature;Humidity" >> "$logfile"
        }
        fi
        temp="$(printf "%2.1f" $(echo "scale=1; $temperature / 1000" | bc) )"
        temp=${temp/./,}
        echo -n $mdate >> "$logfile"
        echo -n "$temp;" >> "$logfile"
        temp="$(printf "%2.1f" $(echo "scale=1; $humidity / 1000" | bc) )"
        temp=${temp/./,}
        echo -n "$temp" >> "$logfile"
        cells=$[$cells +1]
#        echo $cells
        echo >> "$logfile"
      }
      fi

      sleep 5s
      if [ "$cells" -eq 1000000 ]
      then
      {
#        echo WHOOSH
        cells=0
        if [ -f "$logfile" ]
        then
        {
          if ! [ -d "$logdir" ]
          then
          {
            mkdir "$logdir"
          }
          fi
          tstamp=$(date +"%Y_%m_%d")
          mv -v "$logfile" "$logdir/HumidityLog_${tstamp}.csv"
        }
        else
        {
          echo Ошибка. При попытке сохранить лог-файл - сценарий не смог его найти.
          exit 1
        }
        fi
      }
      fi
    done
}

case $1 in

  dht21)
    dht21
  ;;

  h)
    echo Вводи write_log_sensors dht21
  ;;

  *)
    echo Используй ключ h и почитай описание.
  ;;
esac
 
# END

